"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useGame } from "@/src/context/GameContext";
import Navigation from "@/src/components/Navigation";

export default function TutorialPage() {
  const router = useRouter();
  const { soundEnabled } = useGame();

  const playBubbleSound = () => {
    if (soundEnabled) {
      const bubbleAudio = new Audio("/audio/bubble.wav");
      bubbleAudio.play().catch((e) => console.log("Audio play failed:", e));
    }
  };

  const handleStartGame = () => {
    playBubbleSound();
    setTimeout(() => {
      router.push("/category");
    }, 300);
  };

  return (
    <div className="min-h-screen pond-gradient flex flex-col py-4 sm:py-6 px-3 sm:px-4">
      <Navigation showBackButton={true} showProgress={false} />
      
      <div className="flex-1 flex items-center justify-center">
        <div className="w-full max-w-[95%] sm:max-w-2xl md:max-w-3xl">
        
        {/* Header */}
        <div className="nes-container is-dark with-title mb-4 sm:mb-6">
          <p className="title text-xs sm:text-sm md:text-base">How to Play</p>
          <div className="text-center py-3 sm:py-4">
            <div className="mb-2 flex justify-center">
              <i className="nes-icon file is-large"></i>
            </div>
            <p className="text-white text-xs sm:text-sm">
              Learn how to play the AI vs Human guessing game
            </p>
          </div>
        </div>

        {/* Game Rules */}
        <div className="nes-container is-rounded pond-theme mb-4 sm:mb-6">
          <h2 className="text-base sm:text-lg md:text-xl font-bold mb-3 sm:mb-4 flex items-center gap-2">
            <i className="nes-icon trophy is-small"></i>
            Game Objective
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed mb-3">
            Your task is to identify <strong>which content was created by humans</strong> and which was generated by AI from two pieces of content.
          </p>
          <p className="text-xs sm:text-sm leading-relaxed">
            Test your ability to detect AI content across four categories: Text, Images, Audio, and Videos!
          </p>
        </div>

        {/* How to Play */}
        <div className="nes-container is-rounded pond-theme mb-4 sm:mb-6">
          <h2 className="text-base sm:text-lg md:text-xl font-bold mb-3 sm:mb-4 flex items-center gap-2">
            <i className="nes-icon star is-small"></i>
            How to Play
          </h2>
          <div className="space-y-3 sm:space-y-4">
            <div className="flex gap-3">
              <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-[#9b2e83] text-white flex items-center justify-center font-bold text-sm sm:text-base">
                1
              </div>
              <div className="flex-1">
                <h3 className="font-bold text-xs sm:text-sm mb-1">Choose a Category</h3>
                <p className="text-[10px] sm:text-xs opacity-80">
                  Select from Text, Images, Audio, or Videos to start the game
                </p>
              </div>
            </div>

            <div className="flex gap-3">
              <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-[#9b2e83] text-white flex items-center justify-center font-bold text-sm sm:text-base">
                2
              </div>
              <div className="flex-1">
                <h3 className="font-bold text-xs sm:text-sm mb-1">Compare Content</h3>
                <p className="text-[10px] sm:text-xs opacity-80">
                  Carefully examine the content on both sides, looking for human-made characteristics
                </p>
              </div>
            </div>

            <div className="flex gap-3">
              <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-[#9b2e83] text-white flex items-center justify-center font-bold text-sm sm:text-base">
                3
              </div>
              <div className="flex-1">
                <h3 className="font-bold text-xs sm:text-sm mb-1">Make Your Choice</h3>
                <p className="text-[10px] sm:text-xs opacity-80">
                  Click on the side you believe was created by a human
                </p>
              </div>
            </div>

            <div className="flex gap-3">
              <div className="flex-shrink-0 w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-[#9b2e83] text-white flex items-center justify-center font-bold text-sm sm:text-base">
                4
              </div>
              <div className="flex-1">
                <h3 className="font-bold text-xs sm:text-sm mb-1">Get Feedback</h3>
                <p className="text-[10px] sm:text-xs opacity-80">
                  See if your answer is correct and proceed to the next question
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Categories */}
        <div className="nes-container is-rounded pond-theme mb-4 sm:mb-6">
          <h2 className="text-base sm:text-lg md:text-xl font-bold mb-3 sm:mb-4 flex items-center gap-2">
            <i className="nes-icon file is-small"></i>
            Four Categories
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
            <div className="nes-container is-rounded">
              <div className="flex items-center gap-2 mb-2">
                <i className="nes-icon file is-small"></i>
                <h3 className="font-bold text-xs sm:text-sm">Text</h3>
              </div>
              <p className="text-[10px] sm:text-xs opacity-80">
                Compare writing styles in articles, poems, and stories
              </p>
            </div>

            <div className="nes-container is-rounded">
              <div className="flex items-center gap-2 mb-2">
                <i className="nes-icon star is-small"></i>
                <h3 className="font-bold text-xs sm:text-sm">Images</h3>
              </div>
              <p className="text-[10px] sm:text-xs opacity-80">
                Identify authentic artwork, photos, and designs
              </p>
            </div>

            <div className="nes-container is-rounded">
              <div className="flex items-center gap-2 mb-2">
                <i className="nes-icon heart is-small"></i>
                <h3 className="font-bold text-xs sm:text-sm">Audio</h3>
              </div>
              <p className="text-[10px] sm:text-xs opacity-80">
                Distinguish the source of music, sounds, and voices
              </p>
            </div>

            <div className="nes-container is-rounded">
              <div className="flex items-center gap-2 mb-2">
                <i className="nes-icon trophy is-small"></i>
                <h3 className="font-bold text-xs sm:text-sm">Videos</h3>
              </div>
              <p className="text-[10px] sm:text-xs opacity-80">
                Differentiate between video clips and animations
              </p>
            </div>
          </div>
        </div>

        {/* Scoring */}
        <div className="nes-container is-rounded pond-theme mb-4 sm:mb-6">
          <h2 className="text-base sm:text-lg md:text-xl font-bold mb-3 sm:mb-4 flex items-center gap-2">
            <i className="nes-icon coin is-small"></i>
            Scoring System
          </h2>
          <div className="space-y-2 text-xs sm:text-sm">
            <div className="flex items-center gap-2">
              <i className="nes-icon check is-small"></i>
              <span>Each correct answer earns <strong>1 point</strong></span>
            </div>
            <div className="flex items-center gap-2">
              <i className="nes-icon times is-small"></i>
              <span>Wrong answers don't lose points, but don't earn any either</span>
            </div>
            <div className="flex items-center gap-2">
              <i className="nes-icon trophy is-small"></i>
              <span>Each category has <strong>10 questions</strong>, maximum score of 10</span>
            </div>
            <div className="flex items-center gap-2">
              <i className="nes-icon star is-small"></i>
              <span>Complete all 4 categories for a maximum total of 40 points</span>
            </div>
          </div>
        </div>

        {/* Performance Levels */}
        <div className="nes-container is-rounded pond-theme mb-4 sm:mb-6">
          <h2 className="text-base sm:text-lg md:text-xl font-bold mb-3 sm:mb-4 flex items-center gap-2">
            <i className="nes-icon user is-small"></i>
            Rating System
          </h2>
          <div className="space-y-2 text-xs sm:text-sm">
            <div className="flex justify-between items-center">
              <span className="opacity-80">10/10</span>
              <span className="font-bold text-yellow-600 flex items-center gap-2">
                <span>Perfect (Expert)</span>
                <i className="nes-icon trophy is-small"></i>
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="opacity-80">8-9/10</span>
              <span className="font-bold text-green-600 flex items-center gap-2">
                <span>Excellent (Advanced)</span>
                <i className="nes-icon star is-small"></i>
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="opacity-80">5-7/10</span>
              <span className="font-bold text-blue-600 flex items-center gap-2">
                <span>Good (Intermediate)</span>
                <i className="nes-icon thumbs-up is-small"></i>
              </span>
            </div>
            <div className="flex justify-between items-center">
              <span className="opacity-80">0-4/10</span>
              <span className="font-bold text-gray-600 flex items-center gap-2">
                <span>Keep Trying (Beginner)</span>
                <i className="nes-icon heart is-small"></i>
              </span>
            </div>
          </div>
        </div>

        {/* Tips */}
        <div className="nes-container is-rounded is-warning mb-4 sm:mb-6 text-gray-800">
          <h2 className="text-base sm:text-lg md:text-xl font-bold mb-3 sm:mb-4 flex items-center gap-2 text-yellow-800">
            <i className="nes-icon exclamation is-small"></i>
            Useful Tips
          </h2>
          <ul className="space-y-2 text-xs sm:text-sm list-disc list-inside text-gray-800">
            <li>Pay attention to details - AI-generated content often has telltale signs</li>
            <li>Human creations usually have more emotion and personalized expression</li>
            <li>AI content might be too perfect or have unnatural elements</li>
            <li>Take your time - there's plenty of time to think about each question</li>
            <li>Progress is automatically saved so you can continue anytime</li>
          </ul>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col gap-3 sm:gap-4 justify-center">
          <button
            onClick={handleStartGame}
            className="nes-btn is-success text-sm sm:text-base md:text-lg flex items-center justify-center gap-2 py-4 hover:scale-105 transition-transform animate-pulse-slow"
          >
            <i className="nes-icon play is-medium"></i>
            <span>Start Playing Now!</span>
          </button>
          <Link href="/">
            <button className="nes-btn text-xs sm:text-sm flex items-center justify-center gap-2 w-full">
              <i className="nes-icon user is-small"></i>
              <span>Back to Home</span>
            </button>
          </Link>
        </div>

        </div>
      </div>
    </div>
  );
}
